replicaCount: 1

image:
  repository: sergfut
  tag: "v1.0.2-7513857"
  arch: amd64
# Додатково визначте секцію для токену TELE_TOKEN
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true