replicaCount: 1
image:
  repository: sergfut
  tag: "v0.1.0-ae95ed8"
  arch: amd64
# Додатково визначте секцію для токену TELE_TOKEN
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
